### ISSUE TITLE
Some question about the angular loss

### ISSUE THREAD

**Issue by Henry0528** [talreiss/Mean-Shifted-Anomaly-Detection#10]
First,thanks for the great work.There seems some difference in the angular center loss between the paper and the code.
In the paper, the angular center loss is defined as the product of the output of the model and the centered feature c
<img width="316" alt="image" src="https://user-images.githubusercontent.com/61041040/190386063-84dc4e92-3276-44d0-8777-fe2b9dbb203f.png">
While in the code, the angular center loss is defined as the L2 distance between the output and centered feature, which seems the same as the original center loss
<img width="908" alt="image" src="https://user-images.githubusercontent.com/61041040/190387446-873d4dde-f5b2-4535-81a7-0ee778595618.png">

**Comment by talreiss** [comment]
Hi
Please note that optimizing the Euclidean metric when dealing with unit vectors is proportional to optimizing the angular distance multiplied by a constant factor. Therefore, this optimization process is equivalent.
Hope this clarifies your question.

**Comment by Henry0528** [comment]
Thank for your answer！
