### ISSUE TITLE
Seek help to reproduce results.

### ISSUE THREAD

**Issue by bebop96** [talreiss/Mean-Shifted-Anomaly-Detection#14]
Hi!
Thank you for your insightful and valuable work. Actually, I'm having some problems running main.py with default parameters.
I didn't change anything, but the AUC metric is always 0.5. It's very confusing for me. 
Thank you in advance for your kindness and availability.

**Comment by talreiss** [comment]
Hi,

I ran CIFAR-10 again on our end, and reproduced the results. Please re-check if you changed the code, since at the beginning, with the initialized pre-trained model the results were 0.9+.
