### ISSUE TITLE
threshold

### ISSUE THREAD

**Issue by AEP-WYK** [talreiss/Mean-Shifted-Anomaly-Detection#5]
In the abnormal detection stage, you used the method of whether the score exceeded a threshold to judge whether the sample was abnormal. How to determine the threshold?

**Comment by talreiss** [comment]
Hi,
In order to measure the accuracy of our method we use the ROC-AUC metric, for which no threshold is specified. (See https://en.wikipedia.org/wiki/Receiver_operating_characteristic).
